"use client"

import { useEffect, useState } from "react";
import { CursorSVG } from "@/app/lib/cursorSVG";

const GeneratedResponse = ({ response, visibility, lastQuestion, toggleVisibility, type, questionID='' }: { response: any, visibility: boolean, lastQuestion: string, toggleVisibility: any, type: string, questionID: string }) => {

    const [displayResponse, setDisplayResponse] = useState('');
    const [completedTyping, setCompletedTyping] = useState(false);

    useEffect(() => {
        const typeResponse = () => {
            setCompletedTyping(false);
    
            let i = 0;
            const stringResponse = response || "";
    
            const intervalId = setInterval(() => {
                setDisplayResponse(stringResponse.slice(0, i));
    
                i++;
    
                if (i > stringResponse.length) {
                    clearInterval(intervalId);
                    setCompletedTyping(true);
                }
            }, 15);
    
            return () => clearInterval(intervalId);
        };
    
        if (response !== null) {
            typeResponse();
        }
    
    }, [response]);    

    return (
        <div className="">
            {visibility && (
                <div className='w-full rounded-lg border-b-2 border-blue-500 shadow-md px-4 py-3 mt-2 mb-4' style={{backgroundColor: '#edeffa'}}>
                    <div>
                        <div className='flex flex-row items-start justify-between pt-2'>
                            <p className='text-zinc-700 mb-3 font-bold'>{lastQuestion}</p>
                            <p className='font-bold text-grey-500 cursor-pointer scale-x-125' onClick={() => type=='question' ? toggleVisibility(false) : toggleVisibility(questionID, false)}>X</p>
                        </div>

                        <span className="flex flex-row mt-2 mb-1">
                            <p className="text-justify">{displayResponse}</p>
                            {!completedTyping && <CursorSVG />}
                        </span>

                        <span className="flex flex-row items-end justify-end">
                            <h6 className="text-sm text-blue-500 mb-0">Generated by Meta AI</h6>
                        </span>
                    </div>
                </div>
            )}
        </div>
    );
}

export default GeneratedResponse;