# Generated by Django 4.2.7 on 2023-11-11 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='semester',
            new_name='_semester',
        ),
    ]
