# Generated by Django 4.2.7 on 2023-11-13 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_classroom_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('std_id', 'institution')},
        ),
    ]
