# Generated by Django 4.2.7 on 2023-11-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='std_id',
            field=models.IntegerField(verbose_name='Student ID / Faculty ID'),
        ),
    ]
