# Generated by Django 4.2.7 on 2023-11-16 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_classroom_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='course_name',
            field=models.CharField(default=0, max_length=255, verbose_name='Course Name'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='Question')),
                ('topic', models.CharField(max_length=255, verbose_name='Question Topic')),
                ('score', models.IntegerField(default=0, verbose_name='Question Score')),
                ('level', models.CharField(choices=[('Basic', 'Basic'), ('Fundamental', 'Fundamental'), ('Practical', 'Practical'), ('Analytical', 'Analytical'), ('Inventive', 'Inventive'), ('Critical', 'Critical')], max_length=255, verbose_name='Question Level')),
                ('is_knowledge', models.BooleanField(default=False)),
                ('is_comprehensive', models.BooleanField(default=False)),
                ('is_application', models.BooleanField(default=False)),
                ('is_analytical', models.BooleanField(default=False)),
                ('is_evaluative', models.BooleanField(default=False)),
                ('is_synthetic', models.BooleanField(default=False)),
                ('is_answered', models.BooleanField(default=False)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
