# Generated by Django 4.2.7 on 2023-11-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_questiontype_classroom_course_name_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionType',
        ),
        migrations.AddField(
            model_name='question',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
